import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/shared/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "../utils/authOptions";
import SessionProviderWrapper from "./component/shared/SessionProviderWrapper";
// import SessionProviderWrapper from "../components/SessionProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}) {
  // const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <Navbar />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
